Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.16/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from os import sys

sys.stdout = open(os.devnull, "w")
sys.stderr = open(os.devnull, "w")

from os import path
import os

if path.isdir('analysis')== False:
    !git clone https://github.com/courtois-neuromod/anat-processing-book.git analysis
    dir_name = 'analysis'
    analysis = os.listdir(dir_name)

    for item in analysis:
        if item.endswith(".ipynb"):
            os.remove(os.path.join(dir_name, item))
        if item.endswith(".md"):
            os.remove(os.path.join(dir_name, item))

cwd = os.getcwd()
os.chdir('analysis/source')

from tools.data import *
from tools.plot import *
from tools.stats import *

os.chdir(cwd)

# Python imports 
from IPython.display import clear_output
from pathlib import Path
import numpy as np

import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
pd.set_option('display.colheader_justify', 'center')
pd.set_option('display.precision', 1)

data_type = 'brain'
release_version = 'latest'

dataset = Data(data_type)
dataset.download(release_version)

dataset.load()
fig_gm = Plot(dataset, plot_name = 'brain-1')

fig_gm.title = 'Brain qMRI microstructure measures'
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[1], line 3[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mos[39;00m [38;5;28;01mimport[39;00m sys
[0;32m----> 3[0m sys[38;5;241m.[39mstdout [38;5;241m=[39m [38;5;28mopen[39m([43mos[49m[38;5;241m.[39mdevnull, [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m)
[1;32m      4[0m sys[38;5;241m.[39mstderr [38;5;241m=[39m [38;5;28mopen[39m(os[38;5;241m.[39mdevnull, [38;5;124m"[39m[38;5;124mw[39m[38;5;124m"[39m)
[1;32m      6[0m [38;5;28;01mfrom[39;00m [38;5;21;01mos[39;00m [38;5;28;01mimport[39;00m path

[0;31mNameError[0m: name 'os' is not defined
NameError: name 'os' is not defined

